CREATE TABLE train_data (
    id SERIAL PRIMARY KEY,
    cid INTEGER,
    time_feature INTEGER,
    trt INTEGER,
    age INTEGER,
    wtkg FLOAT,
    hemo INTEGER,
    homo INTEGER,
    drugs INTEGER,
    karnof INTEGER,
    oprior INTEGER,
    z30 INTEGER,
    zprior INTEGER,
    preanti INTEGER,
    race INTEGER,
    gender INTEGER,
    str2 INTEGER,
    strat INTEGER,
    symptom INTEGER,
    treat INTEGER,
    offtrt INTEGER,
    cd40 INTEGER,
    cd420 INTEGER,
    cd80 INTEGER,
    cd820 INTEGER
);
CREATE TABLE predictions (
    id SERIAL PRIMARY KEY,
    cid INTEGER,
    time_feature INTEGER,
    trt INTEGER,
    age INTEGER,
    wtkg FLOAT,
    hemo INTEGER,
    homo INTEGER,
    drugs INTEGER,
    karnof INTEGER,
    oprior INTEGER,
    z30 INTEGER,
    zprior INTEGER,
    preanti INTEGER,
    race INTEGER,
    gender INTEGER,
    str2 INTEGER,
    strat INTEGER,
    symptom INTEGER,
    treat INTEGER,
    offtrt INTEGER,
    cd40 INTEGER,
    cd420 INTEGER,
    cd80 INTEGER,
    cd820 INTEGER
);
CREATE TABLE new_data (
    id SERIAL PRIMARY KEY,
    cid INTEGER,
    time_feature INTEGER,
    trt INTEGER,
    age INTEGER,
    wtkg FLOAT,
    hemo INTEGER,
    homo INTEGER,
    drugs INTEGER,
    karnof INTEGER,
    oprior INTEGER,
    z30 INTEGER,
    zprior INTEGER,
    preanti INTEGER,
    race INTEGER,
    gender INTEGER,
    str2 INTEGER,
    strat INTEGER,
    symptom INTEGER,
    treat INTEGER,
    offtrt INTEGER,
    cd40 INTEGER,
    cd420 INTEGER,
    cd80 INTEGER,
    cd820 INTEGER
);
