version: "3.9"

services:
  # Postgres service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: aids
      POSTGRES_PASSWORD: aids
      POSTGRES_DB: aids
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.1
    container_name: mlflow
    environment:
      ARTIFACT_ROOT: /mlflow/artifacts
    volumes:
      - /mlflow_data:/mlflow
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: ["mlflow", "server"]
  # API service
  api:
    build: app/
    container_name: api
    environment:
      DATABASE_URL: postgresql://aids:aids@postgres:5432/aids
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
      PYTHONPATH: /app:/app/api:/app/src:/app/AidsModel
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mlflow