version: "3.9"

services:
  # Postgres service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: aids
      POSTGRES_PASSWORD: aids
      POSTGRES_DB: aids
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # API service
  api:
    build: app/  # Replace with the relative path to your API Dockerfile
    ports:
      - "8080:8080"
      - "5000:5000"
    depends_on:
      - postgres  # Ensure postgres is running before the API
    environment:
      - DATABASE_URL=postgresql://aids:aids@postgres:5432/aids  # Replace credentials and database name
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000  # Adjust port if needed
